export const LandingPageObject = [
  {
    text: "SAVINGS",
    subText:
      "We can help you save and manage your money when you reduce expenditure such as recurring cost.",
    // tabImage: require("../../assets/images/Tab1.png"),
    image: require("../../assets/images/TabPicture1.png"),
    buttonText: "Login",
    button2Text: "Signup",
    onPress: { screenName: "LandingPage2" },
    nextText: ">",
  },
  {
    text: "BILLS PAYMENT",
    subText:
      "Our e-BillsPay is a convenient and efficient payment service that provides multiple billers and institutions, online monetary collections and payments.",
    // tabImage: require("../../assets/images/Tab2.png"),
    image: require("../../assets/images/TabPicture2.png"),
    buttonText: "Login",
    button2Text: "Signup",
    onPress: { screenName: "LandingPage3" },
    previousText: "<",
    nextText: ">",
  },
  {
    text: "LOANS",
    subText:
      "Our low interest personal, car and business loans provide you with the right financing for your needs while guaranteeing you all the security you are looking for.",
    // tabImage: require("../../assets/images/Tab3.png"),
    image: require("../../assets/images/TabPicture3.png"),
    buttonText: "Login",
    button2Text: "Signup",
    onPress: { screenName: "LandingPage4" },
    previousText: "<",
    nextText: ">",
  },
  {
    text: "WALLET",
    subText:
      "Our digital wallet (or electronic wallet) is a financial system that runs on any connected device. It securely stores your payment information and passwords for secure, quick and seamless transactions.",
    // tabImage: require("../../assets/images/Tab4.png"),
    image: require("../../assets/images/TabPicture4.png"),
    buttonText: "Login",
    button2Text: "Signup",
    onPress: { screenName: "LandingPage5" },
    previousText: "<",
    nextText: ">",
  },
  {
    text: "INSTANT BANK TRANSFER",
    subText:
      "We facilitate transferring money from your wallet to any bank account in the country. It is safer than withdrawing and paying in cash.",
    // tabImage: require("../../assets/images/Tab5.png"),
    image: require("../../assets/images/TabPicture3.png"),
    buttonText: "Login",
    button2Text: "Signup",
    onPress: { screenName: "LandingPage6" },
    previousText: "<",
    nextText: ">",
  },
  {
    text: "BUY NOW, PAY LATER",
    subText:
      "Make purchases and spread payments over time. Signup, provide all required information, receive your credit limit and proceed to buy.",
    // tabImage: require("../../assets/images/Tab6.png"),
    image: require("../../assets/images/Tab6Picture.png"),
    buttonText: "Login",
    button2Text: "Signup",
    onPress: { screenName: "LandingPage7" },
    previousText: "<",
    nextText: ">",
  },
  {
    text: "LOYALTY & REWARD",
    subText:
      "Our loyalty and reward system are freely given without restriction to encourage repeat business.",
    // tabImage: require("../../assets/images/Tab7.png"),
    image: require("../../assets/images/Tab7Picture.png"),
    buttonText: "Login",
    button2Text: "Signup",
    onPress: { screenName: "LandingPage8" },
    previousText: "<",
    nextText: ">",
  },
  {
    text: "FIXED DEPOSIT",
    subText:
      "Grow your money with us, we will let you invest a specific amount of money for a fixed period of time, at an agreed interest rate.",
    // tabImage: require("../../assets/images/Tab8.png"),
    image: require("../../assets/images/Tab8Picture.png"),
    buttonText: "Login",
    button2Text: "Signup",
    onPress: { screenName: "LandingPage9" },
    previousText: "<",
  },
];
